- name: Create {{ lldpd_service_account }} service account...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'ldp-lldpd-serviceaccount.yaml') }}"

- name: Ensure {{ lldpd_service_account }} service account exists...
  kubernetes.core.k8s:
    api_version: v1
    kind: ServiceAccount
    name: "{{ lldpd_service_account }}"
    namespace: "{{ lldpd_namespace }}"
    state: present

- name: Create {{ lldpd_service_account }} service account...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'ldp-lldpd-clusterrolebinding.yaml') }}"     

- name: Deploy Lldpd Daemonset...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'ldp-lldpd-daemonset.yaml') }}"

#- name: Wait for Lldpd Daemonset to Deploy...
#  ansible.builtin.import_role:
#    name: common_tasks
#    tasks_from: wait_for_instance.yml
#  vars:
#    instance_name: nfd-instance
#    instance_namespace: "{{ nfd_namespace }}"
#    kind_name: NodeFeatureDiscovery
#    api_operator_version: nfd.openshift.io/v1
#    nvidia: false
