apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ lldpd_name }}
  namespace: {{ lldpd_namespace }}
  labels:
    app: {{ lldpd_app_name }}
spec:
  selector:
    matchLabels:
      app: {{ lldpd_app_name }} 
  template:
    metadata:
      labels:
        app: {{ lldpd_app_name }}
    spec:
      serviceAccountName: {{ lldpd_service_account }}
      hostNetwork: true
      containers:
        - name: lldpd-container
          image: {{ lldpd_image_name }}
          securityContext:
            privileged: true
