apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ node_role }}
  name: 99-{{ node_role }}-kernel-machineconfig
spec:
  kernelArguments:
    - "module_blacklist=irdma"
    - default_hugepagesz={{ default_hugepagesz }}
    - hugepagesz={{ hugepagesz }}
    - hugepages={{ hugepages }}
    - intel_iommu=on
    - iommu=pt
    - pci=realloc=on
