apiVersion: v1
kind: Namespace
metadata:
  name: {{ gpo_namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ gpo_namespace }}
  namespace: {{ gpo_namespace }}
spec:
  targetNamespaces:
    - {{ gpo_namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ gpo_namespace }}
  namespace: {{ gpo_namespace }}
spec:
  channel: {{ gpo_version }}
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
