apiVersion: v1
kind: Namespace
metadata:
  name: {{ nfd_namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd
  namespace: {{ nfd_namespace }}
spec:
  targetNamespaces:
    - {{ nfd_namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: {{ nfd_namespace }}
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
