rail_names:
  - name: snnp_eth_rail1
    mtu: 9216
    pfname: eth_rail1
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail1
  - name: snnp_eth_rail2
    mtu: 9216
    pfname: eth_rail2
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail2
