rail_names:
  - name: snnp-eth-rail0
    mtu: 9216
    pfname: eth_rail0
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail0
  - name: snnp-eth-rail1
    mtu: 9216
    pfname: eth_rail1
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail1
  - name: snnp-eth-rail2
    mtu: 9216
    pfname: eth_rail2
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail2
  - name: snnp-eth-rail3
    mtu: 9216
    pfname: eth_rail3
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail3
  - name: snnp-eth-rail4
    mtu: 9216
    pfname: eth_rail4
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail4
  - name: snnp-eth-rail5
    mtu: 9216
    pfname: eth_rail5
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail5
  - name: snnp-eth-rail6
    mtu: 9216
    pfname: eth_rail6
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail6
  - name: snnp-eth-rail7
    mtu: 9216
    pfname: eth_rail7
    numvfs: 1
    isrdma: true
    linktype: eth
    resourcename: eth_rail7
  
