- name: Base64 Encode Password
  ansible.builtin.shell: mkpasswd -m SHA-512 "{{ core_password }}"
  register: password_hash
  tags: register

- name: Deploy Core Password MachineConfig
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'scp-machineconfig.yaml') }}"
