- name: Deploy NVIDIA Network Operator
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'nno-operator.yaml') }}"

- name: Wait for NVIDIA Network Operator to Deploy...
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: wait_for_operator.yml
  vars:
    operator_name: "{{ nno_namespace }}"
    operator_namespace: "{{ nno_namespace }}"

- name: Deploy NVIDIA Network Operator NicClusterPolicy...
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'nno-{{ nno_type }}-nicclusterpolicy.yaml') }}"

- name: Wait for NVIDIA Network Operator NicClusterPolicy to Deploy...
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: wait_for_instance.yml

  vars:
    instance_name: nic-cluster-policy
    instance_namespace: "{{ nno_namespace }}"
    kind_name: NicClusterPolicy
