apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ node_role }}
  name: 99-{{ node_role }}-kernel-machineconfig
spec:
  kernelArguments:
    - "module_blacklist=irdma"
    - default_hugepagesz=1G
    - hugepagesz=1G
    - hugepages=16
    - intel_iommu=on
    - iommu=pt
    - pci=realloc=on
