- name: 30 second pause to let MCO start processing...
  ansible.builtin.pause:
    seconds: 30
    
- name: Waiting Since {{ lookup("pipe", "date +%r") }} for the MachineConfig to Deploy
  kubernetes.core.k8s_info:
    api_version: '{{ api_operator_version }}'
    kind: '{{ kind_name }}'
    name: '{{ mcp_name }}'
  register: instance_mcp
  until:
    - instance_mcp.resources.0.status is defined
    - instance_mcp.resources.0.status.conditions is defined
    - instance_mcp.resources.0.status.conditions[5].lastTransitionTime is defined
    - instance_mcp.resources.0.status.conditions[5].type == 'Updating'
    - instance_mcp.resources.0.status.conditions[5].status == 'False'
  failed_when: False
  retries: 3000
  delay: 20
