apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  nicConfigurationOperator:
    configurationDaemon:
      containerResources:
      - limits:
          cpu: 1000m
          memory: 10000Mi
        name: nic-configuration-daemon
        requests:
          cpu: 1000m
          memory: 10000Mi
      image: nic-configuration-operator-daemon
      repository: nvcr.io/nvidia/mellanox
      version: network-operator-v26.1.0
    logLevel: debug
    nicFirmwareStorage:
      availableStorageSize: 1Gi
      create: false
      pvcName: nic-fw-storage-pvc
    operator:
      containerResources:
      - limits:
          cpu: 1000m
          memory: 10000Mi
        name: nic-configuration-operator
        requests:
          cpu: 1000m
          memory: 10000Mi
      image: nic-configuration-operator
      repository: nvcr.io/nvidia/mellanox
      version: network-operator-v26.1.0
  nvIpam:
    image: nvidia-k8s-ipam
    repository: nvcr.io/nvidia/mellanox
    version: network-operator-v26.1.0
    enableWebhook: false
  ofedDriver:
    env:
    - name: UNLOAD_STORAGE_MODULES
      value: "true"
    forcePrecompiled: false
    image: doca-driver
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    repository: nvcr.io/nvstaging/mellanox
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    terminationGracePeriodSeconds: 300
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      safeLoad: false
    version: doca3.3.0-26.01-0.4.6.0-1
  spectrumXOperator:
    image: spectrum-x-operator
    repository: nvcr.io/nvidia/mellanox
    version: network-operator-v26.1.0
