apiVersion: v1
kind: Namespace
metadata:
  name: {{ nno_namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ nno_namespace }}
  namespace: {{ nno_namespace }}
spec:
  targetNamespaces:
  - {{ nno_namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ nno_namespace }}
  namespace: {{ nno_namespace }}
spec:
  channel: {{ nno_version }}
  installPlanApproval: Automatic
  name: {{ nno_namespace }}
  source: certified-operators
  sourceNamespace: openshift-marketplace
